#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Check if either "bun" or "yarn" command exists
if command -v bun >/dev/null 2>&1; then
  # "bun" command exists
  bun run lint && bun run test
elif command -v yarn >/dev/null 2>&1; then
  # "yarn" command exists
  yarn lint && yarn test
else
  # Neither "bun" nor "yarn" command found
  echo "Error: Neither 'bun' nor 'yarn' command found." >&2
  exit 1
fi
